# example config
name: Name
mongo:
  db: exampleDB
  credits:
  collections:
    [
    "publication",
    "authors",
    "translations"
    ]
  publication:
    delete_route: false
    fields:
      - Name: Title
        Type: "string"
        Binding: "required"
      - Name: Id
        Type: "int64"
        Binding: "required"